server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      enabled: true

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      httpclient:
        connect-timeout: 3000
        response-timeout: 3s

      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**

        - id: ride-service
          uri: lb://ride-service
          predicates:
            - Path=/api/rides/**

        - id: driver-service
          uri: lb://driver-service
          predicates:
            - Path=/api/drivers/**

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8089/realms/smartride

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,gateway
