server:
  port: 8080

spring:
  application:
    name: api-gateway

  redis:
    host: localhost
    port: 6379

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8089/realms/smartride

  cloud:
    gateway:
      httpclient:
        connect-timeout: 3000
        response-timeout: 3s

      default-filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 10
            redis-rate-limiter.burstCapacity: 20

        - name: CircuitBreaker
          args:
            name: defaultCB
            fallbackUri: forward:/fallback/default

      routes:
         - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**
        - id: ride-service
          uri: lb://RIDE-SERVICE
          predicates:
            - Path=/rides/**

        - id: driver-service
          uri: lb://DRIVER-SERVICE
          predicates:
            - Path=/drivers/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

resilience4j:
  timelimiter:
    instances:
      defaultCB:
        timeout-duration: 3s
        cancel-running-future: true

  circuitbreaker:
    instances:
      defaultCB:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 20
        minimum-number-of-calls: 10
        failure-rate-threshold: 50
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 2s
        permitted-number-of-calls-in-half-open-state: 5
        wait-duration-in-open-state: 15s
