spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**

        - id: ride-service
          uri: lb://ride-service
          predicates:
            - Path=/api/rides/**

        - id: driver-service
          uri: lb://driver-service
          predicates:
            - Path=/api/drivers/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
