server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      httpclient:
        connect-timeout: 3000
        response-timeout: 3s

      default-filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 10
            redis-rate-limiter.burstCapacity: 20

        - name: CircuitBreaker
          args:
            name: defaultCB
            fallbackUri: forward:/fallback/default

      routes:
        - id: ride-service
          uri: lb://RIDE-SERVICE
          predicates:
            - Path=/rides/**

        - id: driver-service
          uri: lb://DRIVER-SERVICE
          predicates:
            - Path=/drivers/**
