server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      enabled: true

      httpclient:
        connect-timeout: 3000
        response-timeout: 3s

      default-filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 10
            redis-rate-limiter.burstCapacity: 20

      routes:
        # ================= AUTH SERVICE =================
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**

        # ================= RIDE SERVICE =================
        - id: ride-service
          uri: lb://RIDE-SERVICE
          predicates:
            - Path=/api/rides/**

        # ================= DRIVER SERVICE =================
        - id: driver-service
          uri: lb://DRIVER-SERVICE
          predicates:
            - Path=/api/drivers/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8089/realms/smartride

  data:
    redis:
      host: localhost
      port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoint:
    gateway:
      enabled: true

  endpoints:
    web:
      exposure:
        include: health,info,gateway
