server:
  port: 8084

spring:
  application:
    name: auth-service
    
keycloak:
  realm: smartride
  auth-server-url: http://localhost:8089
  resource: smartride-auth
  ssl-required: external
  credentials:
    secret: ${KEYCLOAK_CLIENT_SECRET}
