server:
  port: 8084

spring:
  application:
    name: auth-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8089/realms/smartride   # resource server for admin api 

keycloak:
  server-url: http://localhost:8089
  realm: smartride
  client-id: smartride-auth
  client-secret: ${KEYCLOAK_CLIENT_SECRET}
