server:
  port: 8084

spring:
  application:
    name: auth-service

keycloak:
  realm: smartride
  auth-server-url: http://localhost:8080
  resource: smartride-auth
  credentials:
    secret: ${KEYCLOAK_CLIENT_SECRET}
