server:
  port: 8084

spring:
  application:
    name: auth-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8086/realms/smartride

keycloak:
  realm: smartride
  auth-server-url: http://localhost:8086
  resource: smartride-auth
  ssl-required: external
  credentials:
    secret: ${KEYCLOAK_CLIENT_SECRET}
