server:
  port: 8082

spring:
  application:
    name: driver-service

  datasource:
    url: jdbc:postgresql://localhost:5432/driver_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8089/realms/smartride

driver:
  assignment:
    max-retries: 3
    retry-delay-ms: 200
    lock-timeout-ms: 3000
