server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/driver_db
    username: somya
    password: 1234

  jpa:
    hibernate:
      ddl-auto: validate

driver:
  assignment:
    max-retries: 3

