server:
  port: 8082

spring:
  application:
    name: driver-service

  datasource:
    url: jdbc:postgresql://localhost:5432/driver_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

driver:
  assignment:
    max-retries: 3
