server:
  port: 8083

spring:
  application:
    name: notification-service

  kafka:
    consumer:
      group-id: notification-service-group
      max-poll-interval-ms: 300000
      max-poll-records: 50

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8089/realms/smartride

kafka:
  topic:
    notifications: notification.events.v1
  consumer:
    retry-attempts: 3 
