server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ride_db
    username: somya
    password: 1234

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

kafka:
  topic:
    ride-events: ride.lifecycle.events
