server:
  port: 8081

spring:
  application:
    name: ride-service

  datasource:
    url: jdbc:postgresql://localhost:5432/ride_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000

  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8086/realms/smartride

  kafka:
    producer:
      enable-idempotence: true

kafka:
  topic:
    ride-events: ride.lifecycle.events
