server:
  port: 8081

spring:
  application:
    name: ride-service

  datasource:
    url: jdbc:postgresql://localhost:5432/ride_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: false

kafka:
  topic:
    ride-events: ride.lifecycle.events
