server:
  port: 8085

spring:
  application:
    name: safety-fraud-service

redis:
  host: localhost
  port: 6379
  timeout-ms: 2000
  key-prefix: smartride:fraud

kafka:
  topic:
    fraud-events: fraud.detected.events
