server:
  port: 8085

spring:
  application:
    name: safety-fraud-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8089/realms/smartride

  kafka:
    consumer:
      group-id: safety-fraud-group
    producer:
      enable-idempotence: true

redis:
  host: localhost
  port: 6379
  timeout-ms: 2000
  key-prefix: smartride:fraud
  ttl-seconds: 300
  pool:
    max-active: 10
    max-idle: 5
    min-idle: 2

kafka:
  topic:
    fraud-events: fraud.events.v1
